version: '3'
services:
  back:
    container_name: tech_db
    build: back/
    ports:
      - "8090:8090"
    volumes:
      - ./back/pb_migrations/:/pb_migrations
      - ./back/pb_data/:/pb_data/
  front:
    container_name: tech_front
    build: front/
    volumes:
      - ./front/src/:/app/src
      - node_modules:/app/node_modules
    env_file:
      - .env
      
    
volumes:
  node_modules:
  