version: '3'
services:
  back:
    container_name: tech_db
    image: erasme/workshop-techshop-back
    build: back/
    ports:
      - "8090:8090"
    volumes:
      - ./back/pb_migrations/:/pb_migrations
      - ./back/pb_data/:/pb_data/
  front:
    container_name: tech_front
    image: erasme/workshop-techshop-front
    build: front/
    volumes:
      - ./front/src/:/app/src
    ports:
      - "5173:5173"
    env_file:
      - .env
      

  